config/routes.rb
Rails.application.routes.draw do

  root 'user#index' #'registration#index'
  get 'user/index', to: 'user#index'
  get 'user/new', to: 'user#new'
  post 'user/new', to: 'user#thankyou'

  resources :users

end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  validates :companyName, length: { 200 } 
end

app/models/user.rb
class User < ApplicationRecord
  validates :firstName, presence: true, length: { maximum: 100 }
  validates :lastName, presence: true, length: { maximum: 100 }
  VALID_EMAIL_REGEX = /@/
  validates :email, presence: true, :format => /@/
  #validates :dob, dataZprzeszłości, prawidłowaData
  #validates :phoneNumber, prawidłowyTelefon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index

  end

  def new
    @users = User.new
  end

  def show
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oszaleje</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/index.html.erb
<div class ="jumbotron">
  <h1>Użytkownicy</h1>
  <p>Rejestracja<br />
</div>
<%= link_to "Działaj", user_new_path, class: "btn btn-success" %>

app/views/user/new.html.erb
<h1>Add new user (registration)</h1>
<h4> User details</h4>
  <%= form_for(user_new_path) do |f| %>
  <div class='form-group'>
    <%= f.text_field :firstName, placeholder: "First name" %>
    <%= f.text_field :lastName, placeholder: "Last name" %>
    <%= f.email_field :email, placeholder: "E-mail" %><br />
    <%= f.date_field :dob, placeholder: "Date of birth" %><br />
    <%= f.telephone_field :phoneNumber, placeholder: "Phone number" %>
    <%= f.text_field :userStreet, placeholder: "User street" %>
    <%= f.text_field :userCity, placeholder: "User city" %><br />
    <%= f.number_field :userZipCode, placeholder: "User zip code" %>
    <%= f.text_field :userCountry, placeholder: "User country" %>
<h4>Company details</h4>
  <%= f.text_field :companyName, placeholder: "Company name" %><br />
  <%= f.text_field :companyStreet, placeholder: "Company street" %>
  <%= f.text_field :companyCity, placeholder: "Company city" %><br />
  <%= f.number_field :companyZipCode, placeholder: "Company zip code" %>
  <%= f.text_field :companyCountry, placeholder: "Company country" %>
 </div>
 <p><%= submit_tag "DO IT",  class: "btn btn-success"%></p>
<% end %>

app/views/user/thankyou.html.erb
<div class ="jumbotron">
  <h1>Zarejestrowano</h1>
  <p>Możesz wrócić do strony głównej</p>
</div>
<%= link_to 'Home', root_path, class: 'btn btn-warning' %>